# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ce6a3e0ac0e172ad25502fb8301193e9"
application_url = "https://chi-mile-explicitly-targets.trycloudflare.com"
embedded = true
name = "test-app"
handle = "test-app-10944"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://chi-mile-explicitly-targets.trycloudflare.com/auth/callback",
  "https://chi-mile-explicitly-targets.trycloudflare.com/auth/shopify/callback",
  "https://chi-mile-explicitly-targets.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "test-shop-vi.myshopify.com"
automatically_update_urls_on_dev = true
